from pydantic import BaseModel
from typing import List, Dict, Optional


class AIDetectionPayload(BaseModel):   
    text: str = "AI Detection is a process to determine if text is generated by AI or written by a human. This is a default text for testing purposes."


class TextGenerationPayload(BaseModel):
    text: str
    system_message: Optional[str] = None
    conversation_history: Optional[List[Dict[str, str]]] = None
    max_new_tokens: int = 256
    temperature: float = 0.7


class PromptEvaluationPayload(BaseModel):
    prompt: str
