from pydantic import BaseModel


class AIDetectionPayload(BaseModel):   
    text: str = "AI Detection is a process to determine if text is generated by AI or written by a human. This is a default text for testing purposes."
